### ISSUE TITLE
Erros compiling in ESPHome

### ISSUE THREAD

**Issue by readylan** [rnauber/ESPHomeMatrixLED#10]
Hi,
thanks for sharing this great work !
I have errors compiling for the M5 Atom Matrix:
(ESPhome 1.5.2)

```
src/main.cpp: In lambda function:
src/main.cpp:529:18: error: 'class MatrixLedScrollingDisplay' has no member named 'set_addr_light'
       matrixled->set_addr_light((light::AddressableLight *) &it);
                  ^
src/main.cpp:530:18: error: 'class MatrixLedScrollingDisplay' has no member named 'set_width'
       matrixled->set_width(5);
                  ^
src/main.cpp:531:18: error: 'class MatrixLedScrollingDisplay' has no member named 'set_height'
       matrixled->set_height(5);
                  ^
src/main.cpp:542:24: error: 'class MatrixLedScrollingDisplay' has no member named 'set_fg_color'
             matrixled->set_fg_color(light::ESPColor(0, 255, 0, 0)); 
                        ^
src/main.cpp:544:24: error: 'class MatrixLedScrollingDisplay' has no member named 'set_fg_color'
             matrixled->set_fg_color(light::ESPColor(255, 0, 0, 0));
                        ^
src/main.cpp:546:24: error: 'class MatrixLedScrollingDisplay' has no member named 'set_fg_color'
             matrixled->set_fg_color(current_color);
                        ^
*** [.pioenvs/co2/src/main.cpp.o] Error 1
========================== [FAILED] Took 6.26 seconds ==========================


```
I'm not sure if doing all right: the only two things I've changed are:
1) the name of library in yaml file:
```
includes:
    - my_matrixled_display.h
to
includes:
    - my_matrixled_scrolling_display.h
```
2) in lambda definition for light platform: 
```
static auto matrixled = new MatrixLedDisplay();
to
static auto matrixled = new MatrixLedScrollingDisplay();
```
Sorry, I'm not familiar with C languaje and can't continue testing.
Can you please tell me what am I doing wrong?

Regards,

Eduardo

**Comment by apolselli** [comment]
Hi, my example for M5 Atom Marquee compiled against ESPHome 1.14.3 and previous ESPHomeMatrixLED version. It should be updated since this changeset
https://github.com/rnauber/ESPHomeMatrixLED/commit/100495a44061166078cece32b2be1fda6a278217#diff-b481e3fef266f746cacccecc808f42c0
but now I can't.

However, the changes that support ESPHome 1.15 are already in the matrixleddemo.yaml example.

First option: Start directly from it, take from the atom_matrix exampe just the light configurations and other specific parts that support the M5Atom Matrix (matrixwidth, matrixheight and font should be enough) and try to mix the things well

**Comment by apolselli** [comment]
Second option: just use my fork of 6 months ago https://github.com/apolselli/ESPHomeMatrixLED
and build it with ESPHome 1.14.3 (or any other 1.14.x)

**Comment by rnauber** [comment]
Hi,
as I cannot test the M5 Atom Marquee example and it is broken, I choose to remove it for now. Feel free to sumbit a PR with an up to date version, as @apolselli suggested:

> First option: Start directly from it, take from the atom_matrix exampe just the light configurations and other specific parts that support the M5Atom Matrix (matrixwidth, matrixheight and font should be enough) and try to mix the things well.

Thank you!

**Comment by apolselli** [comment]
Hi @readylan and @rnauber ,
in https://github.com/rnauber/ESPHomeMatrixLED/pull/11
you can find an up to date version of my M5 Atom Marquee example that now supports the latest changes.
Since I couldn't manage to make the neopixelbus work again with this version of ESPHomeMatrixLED, I switched to the fastled_clockless platform, and it does the job.

**Comment by rnauber** [comment]
Great! If you have a short GIF of it in action, feel free to add it to the readme.
Thanks,
Richard
